### ISSUE TITLE
a problem about config

### ISSUE THREAD

**Issue by xxtars** [MartinXM/TPS#2]
When using imagenet pre-trained model and k400 pre-trained model, are you using the same config?

- configs/recognition/tps/swin_tiny_2D_patch244_tps_sthv2_1k.py

Thanks

**Comment by MartinXM** [comment]
Yes, the only difference is the path of the pre-trained model.

**Comment by xxtars** [comment]
I see that the train_pipeline config is a little different from video swin transformer:

TPS:
-     dict(type='Flip', flip_ratio=0.5, lazy_label=[86,87,93,94,166,167]),
-     dict(type='Imgaug', transforms='default'),

Swin:
-     dict(type='Flip', flip_ratio=0),
-     dict(type='Imgaug', transforms=[dict(type='RandAugment', n=4, m=7)]),

Does it have a big impact on the experiment? Is this to fit two different pre-trained models or to find that the tiny model does not require stronger data augmentation.

**Comment by MartinXM** [comment]
This change fits the sthv1 and sthv2 datasets. In my experiments for Swin-T TPS and Swin-B TPS it works a little bit better than Swin's config.

**Comment by xxtars** [comment]
Thanks so mush!!!
