### ISSUE TITLE
how to show the featuremap with gradcam?

### ISSUE THREAD

**Issue by batman47steam** [MartinXM/TPS#4]
Hi, can you tell me how to get the visualization result like this , thanks in advance
![image](https://user-images.githubusercontent.com/36287035/215328883-75c78d9a-6cb7-4898-8a51-40874348f472.png)

**Comment by MartinXM** [comment]
Please check demo/demo_gradcam.py

**Comment by batman47steam** [comment]
Thanks for the answer , I want to try the demo_gradcam with swin_tiny_2D_patch244_tps_k400_1k.py which pretained model should I use ? Directly use the pretained model from video swin transformer ? 

No pretrained model for the config file swin_tiny_2D_patch244_tps_k400_1k.py

**Comment by MartinXM** [comment]
Please first train TPS model using our code, then you can visualize feature map with gradcam.
