### ISSUE TITLE
About Pre-trained models of k400

### ISSUE THREAD

**Issue by TitaniumOne** [MartinXM/TPS#5]
Thanks for your great work!
Could you provide the pre-trained models of k400?

**Comment by MartinXM** [comment]
we provide k400 pretrained model on modelscope，please check
https://modelscope.cn/models/damo/cv_pathshift_action-recognition/summary

Hao Liu ***@***.***>于2023年2月11日 周六下午3:30写道：

**Comment by TitaniumOne** [comment]
> 
Sorry, I can not find out it on modelscope. Can you give me a specific link?

**Comment by MartinXM** [comment]
![image](https://user-images.githubusercontent.com/6717931/221521586-b46d110e-dc28-4ea4-b6af-b99ed1a1b03d.png)

**Comment by TitaniumOne** [comment]
你好，请问这个模型可以下载到我本地去使用吗？


| |
刘昊
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 02/27/2023 17:11 |
| To | ***@***.***> |
| Cc | Hao ***@***.***> ,
***@***.***> |
| Subject | Re: [MartinXM/TPS] About Pre-trained models of k400 (Issue #5) |
