### ISSUE TITLE
About the pretrained models.

### ISSUE THREAD

**Issue by xh9807** [MartinXM/TPS#7]
Thanks for your outstanding work! I have some questions about the training process. 
If I want to train PST-T on sth-sthv1, I should directly use the pretrained model of Swin-T on IN-1K as the _<PRETRAIN_MODEL>_? And could you provide the loadable pretrained model of PST-T on K400? 
Thank you again for your work.

**Comment by MartinXM** [comment]
Yes, you can use IN-1K directly for pretrain_model. The PST-T on K400 weight is on the modelscope https://modelscope.cn/models/damo/cv_pathshift_action-recognition/summary

**Comment by xh9807** [comment]
Thanks for your reply. I try to get the pretrained model on K400 from ModelScope. So I can use K400 weight on my machine by downloading _pytorch_model.pt_ in the following figure?  Is the method that I obtain the model correct？
![image](https://user-images.githubusercontent.com/45615035/221544847-8dc9e0c5-c798-4b7e-85b6-40ea1e66fa0d.png)

**Comment by MartinXM** [comment]
Yes, you can use this checkpoint, it should work with this code implementation. If you have any problems, please let me know.

**Comment by davimedio01** [comment]
Hi guys. I'm having problems loading the pre-trained model into ModelScope's K400, as shown in the following image. The model.state_dict and model_pretrained.state_dict have the same lenght of 195 with this approach, but i'm missing something in temporal aspect...

![Image](https://github.com/user-attachments/assets/604228c0-1148-4513-bcc7-839a217264b1)

I'm testing the model directly via code, without using directly mmaction2. And, another question: just the torch.nn.Sequential is needed to join backbone TPS with a I3D Head?
torch 1.10.0 // cuda 11.3 // ubuntu 22.04 wsl

**Comment by davimedio01** [comment]
I fixed this problem by changing the hyperparameter from ```PATCH_SIZE = (4, 4, 4)``` to ```PATCH_SIZE = (2, 4, 4)```.
torch 1.10.0 // cuda 11.3 // ubuntu 22.04 wsl
