### ISSUE TITLE
Why don't you use the zero padding in channel shift?

### ISSUE THREAD

**Issue by leexinhao** [MartinXM/TPS#8]
TSM:
![image](https://user-images.githubusercontent.com/48858574/222964119-c5a76275-7e1a-49be-8449-1fe5998377c7.png)
your implement of channel shift:
```python
out[:, 1: ,:, :, :, :fold] = feat[:, :-1, :, :, :, :fold]  # shift left
out[:, :-1 ,:, :, :, fold:2*fold] = feat[:, 1:, :, :, :, fold:2*fold]  # shift right 
```
I understand that your implementation is a little different from TSM's, does that affect performance?

**Comment by MartinXM** [comment]
Hi, we found using this padding works better than zero padding for our model, therefore we use this implementation.

**Comment by leexinhao** [comment]
Thank you. In addition, have you ever tried to apply temporal patch shift to other image classification models? I tried in ConvNeXt, but couldn't get as good a result as Swin transformer, which I guess is probably because you used 16x7x7 relative position coding in swin2d, or do you know of any other possible reasons?

**Comment by MartinXM** [comment]
That's correct. We found relative positon encoding is important for tracking where you shift the patches. You may add similar mechanisms for ConvNeXt to see whether you can get better results.
